"""empty message

Revision ID: 270a20d5efcf
Revises: 61366fc987cd
Create Date: 2023-05-11 01:00:15.596785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270a20d5efcf'
down_revision = '61366fc987cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
