"""change followers to following

Revision ID: 3d2088c7cc6f
Revises: 7b1e440b794a
Create Date: 2023-05-09 06:06:05.350400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2088c7cc6f'
down_revision = '7b1e440b794a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followering',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_followering_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_followering_follower_id_users'))
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='fk_followers_followed_id_users'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_followers_follower_id_users')
    )
    op.drop_table('followering')
    # ### end Alembic commands ###
