"""updated like and user model

Revision ID: 785c3c3a1b08
Revises: a9e095cd5562
Create Date: 2023-05-10 22:40:54.301632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785c3c3a1b08'
down_revision = 'a9e095cd5562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
