"""empty message

Revision ID: 86bff5742ee0
Revises: 4619fd898c57
Create Date: 2023-05-15 04:07:24.922600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bff5742ee0'
down_revision = '4619fd898c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_one_seen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_two_seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('user_two_seen')
        batch_op.drop_column('user_one_seen')

    # ### end Alembic commands ###
