"""renamed followering to following

Revision ID: a9e095cd5562
Revises: 3d2088c7cc6f
Create Date: 2023-05-09 06:15:35.982012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e095cd5562'
down_revision = '3d2088c7cc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_following_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_following_follower_id_users'))
    )
    op.drop_table('followering')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followering',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='fk_followering_followed_id_users'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_followering_follower_id_users')
    )
    op.drop_table('following')
    # ### end Alembic commands ###
